### PR TITLE
Update java base image to jdk 14.0.2

### PR DESCRIPTION
**Pull request by mark-idleman**
Updates base java version to the latest stable release (march 2020, 14.0.2). Should not affect router behavior, just opens up a lot of new options for us.

### CODE REVIEW

**Comment by kaelgreco** [comment]
lol is that it?

**Comment by mark-idleman** [comment]
@kaelgreco as far as I can tell, yes! ;) I'm just going to build 1 region's image with this base image to make sure nothing breaks, but otherwise nothing else should need to change (aside from anyone working on this repo needing to update their local Java installation, of course)

**Comment by mark-idleman** [comment]
Confirmed that this works! Added it to the mega-branch that includes all the new GH changes, and built an image that I can run locally without issue for Sac.

Build w/ image name here: https://console.cloud.google.com/cloud-build/builds/01bf13c1-1d6e-4478-b9a0-9639e2c2206b?project=model-159019

**Review by kaelgreco — APPROVED** [review]
love it

**Comment by mark-idleman** [comment]
Here's what was needed to use this w/ the new versions of the router DMs: https://github.com/replicahq/model/pull/2936/commits/241ef725f4d7a8d909889dd7c1412420948ccfbc

The only change here other than bumping the base image tag is to remove the `-Xconcurrentio` flag from all of the Java commands we run in our new router-related docker images. This flag has been [removed](https://bugs.openjdk.java.net/browse/JDK-8213768) from Java and the JVM yells at you if you use it 😂

**Pull request merged**
